---
title: "Data Access"
page-layout: full
sidebar: false
toc: false
title-block-banner: true
---

## Example Watershed Attributes

This is a **_partial list_** of watershed attributes that are included in Global RIver-lanD (GRID) Database.

| **Feature name**        | **Unit**                        | **Category**   |
| ----------------------- | ------------------------------- | -------------- |
| Runoff                  | mm per month                    | hydrology      |
| Soil moisture           | m<sup>3</sup> per m<sup>3</sup> | hydrology      |
| Temperature             | Celsius                         | climate        |
| Precipitation           | mm per month                    | climate        |
| Watershed area          | km<sup>2</sup>                  | geomorphology  |
| Erosion rate            | mm per year                     | geomorphology  |
| Elevation               | meter                           | geomorphology  |
| Slope                   | degree                          | geomorphology  |
| Aspect                  | degree                          | geomorphology  |
| Soil organic carbon     | g per kg                        | soil chemistry |
| Soil pH                 | pH unit                         | soil chemistry |
| Evaporite               | percentage                      | geology        |
| Carbonate sediment      | percentage                      | geology        |
| Siliciclastic sediment  | percentage                      | geology        |
| Pyroclastic sediment    | percentage                      | geology        |
| Mixed sediment          | percentage                      | geology        |
| Unconsolidated sediment | percentage                      | geology        |
| Igneous basic           | percentage                      | geology        |
| Igneous intermediate    | percentage                      | geology        |
| Igneous acid            | percentage                      | geology        |
| Metamorphic             | percentage                      | geology        |
| Impervious surface area | percentage                      | land use       |
| Population density      | \# per km<sup>2</sup>           | land use       |
| Cultivated vegetation   | percentage                      | land use       |
| Urban                   | percentage                      | land use       |
| Trees                   | percentage                      | land cover     |
| Shrubs                  | percentage                      | land cover     |
| Herbaceous vegetation   | percentage                      | land cover     |
| Flooded vegetation      | percentage                      | land cover     |
| Snow ice                | percentage                      | land cover     |
| Barren                  | percentage                      | land cover     |
| Water                   | percentage                      | land cover     |


## Data Access

This section is under construction. Stay tuned. If you would like to submit a database or begin working with us, please consider reaching out to the [Mangement Team](/people/people.qmd)